#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_input high autosync/install-dir || true
db_go

db_input high autosync/public-host || true
db_input high autosync/frontend-port || true
db_input medium autosync/pull-llm-model || true
db_input high autosync/admin-email || true
db_input high autosync/admin-password || true
db_go

exit 0
