"""remove password from users

Revision ID: 040df7703298
Revises: be69444d20eb
Create Date: 2026-08-16 13:54:53.025527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040df7703298'
down_revision = 'be69444d20eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
