"""contract catalog: reusable contract with parts and labor norms

Revision ID: 0f72e900e34e
Revises: 50f8b1f735bf
Create Date: 2026-08-17 19:21:07.590993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0f72e900e34e'
down_revision = '50f8b1f735bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_labor_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=512), nullable=False),
    sa.Column('vehicle_make', sa.String(length=128), nullable=True),
    sa.Column('vehicle_model', sa.String(length=128), nullable=True),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_labor_norms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_labor_norms_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_labor_norms_operation_name'), ['operation_name'], unique=False)

    op.create_table('contract_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_parts_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_parts_contract_id'), ['contract_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contragent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_contragent_id'), ['contragent_id'], unique=False)
        batch_op.create_foreign_key('fk_contracts_contragent_id', 'contragents', ['contragent_id'], ['id'])
        batch_op.drop_column('parsed_lines')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_lines', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint('fk_contracts_contragent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_contragent_id'))
        batch_op.drop_column('contragent_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('contract_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_parts_contract_id'))
        batch_op.drop_index(batch_op.f('ix_contract_parts_article'))

    op.drop_table('contract_parts')
    with op.batch_alter_table('contract_labor_norms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_labor_norms_operation_name'))
        batch_op.drop_index(batch_op.f('ix_contract_labor_norms_contract_id'))

    op.drop_table('contract_labor_norms')
    # ### end Alembic commands ###
