"""add vehicle_model to hourly rate tables

Revision ID: 1242c78841b2
Revises: 164fea5110cd
Create Date: 2026-08-24 20:38:58.316996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1242c78841b2'
down_revision = '164fea5110cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_hourly_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_model', sa.String(length=128), nullable=True))

    with op.batch_alter_table('contragent_hourly_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_model', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contragent_hourly_rates', schema=None) as batch_op:
        batch_op.drop_column('vehicle_model')

    with op.batch_alter_table('contract_hourly_rates', schema=None) as batch_op:
        batch_op.drop_column('vehicle_model')

    # ### end Alembic commands ###
