"""add article_normalized to contract_parts

Revision ID: 164fea5110cd
Revises: 898ca7ccece8
Create Date: 2026-08-24 11:54:43.736013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164fea5110cd'
down_revision = '898ca7ccece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_normalized', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_contract_parts_article_normalized'), ['article_normalized'], unique=False)

    # ### end Alembic commands ###

    # Бэкфилл для уже загруженных каталогов (реальные данные заказчика,
    # загруженные до этой миграции) — без него нормализация работала бы
    # только для новых импортов, а старые остались бы NULL и не участвовали
    # бы в сопоставлении.
    #
    # Импортируем app.services.matcher.normalize_article() вместо того,
    # чтобы переписывать ту же логику сырым SQL (REPLACE/UPPER) — первая
    # версия этой миграции так и делала, и уже разъехалась с Python-версией
    # в тот же день, когда normalize_article() расширили (кириллица-омоглифы,
    # точки/слэши/подчёркивания) — синхронизировать два места вручную
    # навсегда ненадёжно. flask db upgrade грузит полное Flask-приложение,
    # так что app-контекст для импорта уже есть.
    from app.services.matcher import normalize_article

    bind = op.get_bind()
    contract_parts = sa.table(
        "contract_parts",
        sa.column("id", sa.Integer),
        sa.column("article", sa.String),
        sa.column("article_normalized", sa.String),
    )
    rows = bind.execute(sa.select(contract_parts.c.id, contract_parts.c.article).where(contract_parts.c.article.isnot(None)))
    for row_id, article in rows:
        normalized = normalize_article(article)
        if normalized:
            bind.execute(
                contract_parts.update().where(contract_parts.c.id == row_id).values(article_normalized=normalized)
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_parts_article_normalized'))
        batch_op.drop_column('article_normalized')

    # ### end Alembic commands ###
