"""add ozon_sku and 7-day sales stats to products

Revision ID: 3ccd1d35bd74
Revises: 47af12d300b0
Create Date: 2026-08-16 22:01:42.117444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccd1d35bd74'
down_revision = '47af12d300b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozon_sku', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('units_sold_7d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revenue_7d', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_ozon_sku'), ['ozon_sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_ozon_sku'))
        batch_op.drop_column('revenue_7d')
        batch_op.drop_column('units_sold_7d')
        batch_op.drop_column('ozon_sku')

    # ### end Alembic commands ###
