"""initial schema

Revision ID: 499f52232002
Revises: 
Create Date: 2026-08-06 09:11:56.178817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499f52232002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'FAILED', name='documentprocessingstatus'), nullable=False),
    sa.Column('parsed_lines', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_ozon_product_id'), ['ozon_product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('own_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('own_position', sa.Integer(), nullable=True),
    sa.Column('own_sales_last_7d', sa.Integer(), nullable=True),
    sa.Column('competitor_min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('competitor_avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('competitor_raw_data', sa.JSON(), nullable=True),
    sa.Column('suggested_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggestion_reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='pricesuggestionstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_product_id'), ['product_id'], unique=False)

    op.create_table('repair_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'MATCHING', 'NEEDS_REVIEW', 'REVIEWED', 'FAILED', name='repairorderstatus'), nullable=False),
    sa.Column('parsed_lines', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_document_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_orders_contract_id'), ['contract_id'], unique=False)

    op.create_table('part_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=False),
    sa.Column('contract_article', sa.String(length=128), nullable=True),
    sa.Column('contract_name', sa.String(length=512), nullable=True),
    sa.Column('matched_article', sa.String(length=128), nullable=True),
    sa.Column('matched_name', sa.String(length=512), nullable=True),
    sa.Column('matched_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Enum('EXACT', 'CROSS_REF', 'LLM_GUESS', name='confidencelevel'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_match_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_matches_repair_order_id'), ['repair_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_matches_repair_order_id'))

    op.drop_table('part_matches')
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_orders_contract_id'))

    op.drop_table('repair_orders')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_snapshots_product_id'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_ozon_product_id'))

    op.drop_table('products')
    op.drop_table('contracts')
    # ### end Alembic commands ###
