"""contragent per-make hourly rates

Revision ID: 4f8371a2b279
Revises: e166a72fd646
Create Date: 2026-08-19 12:28:40.390166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8371a2b279'
down_revision = 'e166a72fd646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contragent_hourly_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_make', sa.String(length=128), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contragent_id'], ['contragents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contragent_hourly_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contragent_hourly_rates_contragent_id'), ['contragent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contragent_hourly_rates_vehicle_make'), ['vehicle_make'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contragent_hourly_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contragent_hourly_rates_vehicle_make'))
        batch_op.drop_index(batch_op.f('ix_contragent_hourly_rates_contragent_id'))

    op.drop_table('contragent_hourly_rates')
    # ### end Alembic commands ###
