"""add contract content_hash for duplicate-upload detection

Revision ID: 898ca7ccece8
Revises: 4f8371a2b279
Create Date: 2026-08-21 01:19:41.538736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898ca7ccece8'
down_revision = '4f8371a2b279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
