"""add contragents, labor catalog, labor lines, repair order vehicle fields

Revision ID: b31f8e1ea079
Revises: a1f4c8e2b7d3
Create Date: 2026-08-07 22:11:07.993299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31f8e1ea079'
down_revision = 'a1f4c8e2b7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contragents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('labor_catalog_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_make', sa.String(length=128), nullable=False),
    sa.Column('vehicle_model', sa.String(length=128), nullable=True),
    sa.Column('operation_name', sa.String(length=512), nullable=False),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_catalog_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_catalog_entries_vehicle_make'), ['vehicle_make'], unique=False)
        batch_op.create_index(batch_op.f('ix_labor_catalog_entries_vehicle_model'), ['vehicle_model'], unique=False)

    op.create_table('labor_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('qty', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('matched_operation_name', sa.String(length=512), nullable=True),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Enum('EXACT', 'CROSS_REF', 'LLM_GUESS', name='confidencelevel'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('raw_match_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_lines_repair_order_id'), ['repair_order_id'], unique=False)

    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contragent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_make', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('vehicle_model', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('vehicle_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_vin', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_repair_orders_contragent_id'), ['contragent_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_repair_orders_contragent_id_contragents', 'contragents', ['contragent_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_repair_orders_contragent_id_contragents', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_repair_orders_contragent_id'))
        batch_op.drop_column('vehicle_vin')
        batch_op.drop_column('vehicle_year')
        batch_op.drop_column('vehicle_model')
        batch_op.drop_column('vehicle_make')
        batch_op.drop_column('contragent_id')

    with op.batch_alter_table('labor_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_lines_repair_order_id'))

    op.drop_table('labor_lines')
    with op.batch_alter_table('labor_catalog_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_catalog_entries_vehicle_model'))
        batch_op.drop_index(batch_op.f('ix_labor_catalog_entries_vehicle_make'))

    op.drop_table('labor_catalog_entries')
    op.drop_table('contragents')
    # ### end Alembic commands ###
