"""add order_number and order_date to repair_orders

Revision ID: b6def67354ca
Revises: 1242c78841b2
Create Date: 2026-08-25 00:48:42.623037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6def67354ca'
down_revision = '1242c78841b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('order_date')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
