"""add nomenclature entries and part_match enrichment fields

Revision ID: be69444d20eb
Revises: b31f8e1ea079
Create Date: 2026-08-07 23:29:48.055352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be69444d20eb'
down_revision = 'b31f8e1ea079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomenclature_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('cat_number', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('stock_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reserved_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('in_production_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warehouse', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nomenclature_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomenclature_entries_cat_number'), ['cat_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomenclature_entries_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomenclature_entries_name'), ['name'], unique=False)

    with op.batch_alter_table('part_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomenclature_code', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_cat_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_manufacturer', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_unit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_stock_qty', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_reserved_qty', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_in_production_qty', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_ordered_qty', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_warehouse', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('nomenclature_source', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_matches', schema=None) as batch_op:
        batch_op.drop_column('nomenclature_source')
        batch_op.drop_column('nomenclature_warehouse')
        batch_op.drop_column('nomenclature_ordered_qty')
        batch_op.drop_column('nomenclature_in_production_qty')
        batch_op.drop_column('nomenclature_reserved_qty')
        batch_op.drop_column('nomenclature_stock_qty')
        batch_op.drop_column('nomenclature_unit')
        batch_op.drop_column('nomenclature_manufacturer')
        batch_op.drop_column('nomenclature_cat_number')
        batch_op.drop_column('nomenclature_code')

    with op.batch_alter_table('nomenclature_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomenclature_entries_name'))
        batch_op.drop_index(batch_op.f('ix_nomenclature_entries_code'))
        batch_op.drop_index(batch_op.f('ix_nomenclature_entries_cat_number'))

    op.drop_table('nomenclature_entries')
    # ### end Alembic commands ###
