"""contract archive flag and per-make hourly rates

Revision ID: c3dcb43de777
Revises: 0f72e900e34e
Create Date: 2026-08-18 00:06:21.758654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dcb43de777'
down_revision = '0f72e900e34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_hourly_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_make', sa.String(length=128), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_hourly_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_hourly_rates_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_hourly_rates_vehicle_make'), ['vehicle_make'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('contract_hourly_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_hourly_rates_vehicle_make'))
        batch_op.drop_index(batch_op.f('ix_contract_hourly_rates_contract_id'))

    op.drop_table('contract_hourly_rates')
    # ### end Alembic commands ###
