"""remove user auth system

Revision ID: e166a72fd646
Revises: c3dcb43de777
Create Date: 2026-08-18 02:05:04.552301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e166a72fd646'
down_revision = 'c3dcb43de777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_history', schema=None) as batch_op:
        batch_op.drop_column('actor_id')
        batch_op.drop_column('actor_email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=8), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    with op.batch_alter_table('record_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('actor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_record_history_actor_id_users', 'users', ['actor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
